image: 'maven:3-jdk-8'
stages:
  - test
  - build
services:
  - 'mysql:8.0'
  - 'mongo:4.0'
variables:
  MYSQL_DATABASENAME: "cplayersdb"
  MYSQL_URL: "jdbc:mysql://localhost:3306/cplayersdb?createDatabaseIfNotExist=true"
  MYSQL_USERNAME: "admin"
  MYSQL_PASSWORD: "admin123"
  MYSQL_ROOT_PASSWORD: "root"
  MONGO_DATABASENAME: "cricdb"
  MONGO_HOST: "localhost"
  MONGO_PORT: "27017"
cache:
  paths:
    - .m2/repository
    -  target
maven-test:
  stage: test
  script: "mvn test"
maven-build:
  stage: build
  script: "mvn clean package"
  artifacts:
    paths:
      - target/*.jar